In [8]:
import os
import sys
import re

import numpy as np
import pandas as pd

from pathlib import Path

In [18]:
sys.path.insert(
    0,
    str(Path("../../lift-analyzer-tool").resolve())
)

In [24]:
import src as liftanalyzer

In [19]:
EXERCISE = "deadlift"
# put the file in the data folder
ESTIMATIONS_FILE = "deadlift-estimations-rpe-marked.csv"

In [20]:
csv_path = os.getcwd() / Path("data/" + ESTIMATIONS_FILE)
df = pd.read_csv(csv_path)

In [21]:
df.sample(10)

,filename,frame,time_s,weight,height,rpe,detected,img0_x,img0_y,img0_z,...,world29_z,world30_x,world30_y,world30_z,world31_x,world31_y,world31_z,world32_x,world32_y,world32_z
2040,thor-501kg_rpe9_204cm.mp4,8,0.2983,501.0,204.0,9,1,0.500480,0.538566,-0.662342,...,-0.047977,-0.255683,0.532225,-0.093844,0.245220,0.582721,-0.123020,-0.327447,0.488036,-0.199945
6892,singleton_198cm_420kg_rpe7.mp4,37,1.2507,420.0,198.0,7,1,0.479527,0.254207,-0.314961,...,0.069181,-0.205664,0.730320,0.043826,0.270943,0.768183,-0.011109,-0.244530,0.736770,-0.052204
5095,shaw500training2_200cm_rpe8.mp4,2,0.0674,NaN,200.0,8,1,0.466733,0.461094,-0.601939,...,-0.014415,-0.276983,0.472099,0.009894,0.241975,0.585318,-0.082804,-0.333068,0.498127,-0.072506
8731,elbel_370kg_rpe7.mp4,58,1.9720,370.0,NaN,7,1,0.502442,0.179085,-0.149760,...,0.010257,-0.131225,0.786906,0.050396,0.140840,0.813580,-0.065757,-0.217910,0.791158,-0.016203
1584,deadlift_6_rpe5.mp4,59,1.9686,NaN,NaN,5,1,0.514993,0.142114,0.058212,...,0.334323,0.081986,0.790221,0.039701,-0.057072,0.739811,0.387609,0.176039,0.766991,0.042338
6022,eddie_williams_400kg_193cm_rpe8.mp4,120,4.0449,400.0,193.0,8,1,0.492009,0.264100,-0.358847,...,-0.011914,-0.080811,0.740193,0.013319,0.174430,0.762027,-0.085771,-0.134486,0.730789,-0.078606
1745,thor-120kg_rpe5_204cm.mp4,3,0.1136,120.0,204.0,5,1,0.599097,0.414407,-0.653970,...,-0.106476,-0.132284,0.443066,0.281247,0.424624,0.559480,-0.117768,-0.073731,0.482388,0.254811
7238,g_bilton_440kg_200cm_rpe9.mp4,138,4.6920,440.0,200.0,9,1,0.503408,0.239923,-0.304072,...,0.020196,-0.206521,0.612139,0.014412,0.225300,0.680420,-0.031218,-0.240134,0.622218,-0.063215
3789,shaw_car6_200cm_rpe7.mp4,0,0.0000,NaN,200.0,7,1,0.393433,0.337586,-0.702917,...,-0.085182,-0.221634,0.512487,-0.035568,0.189407,0.648233,-0.174836,-0.282438,0.517541,-0.129267
4038,shaw_car10_200cm_rpe8.mp4,34,1.1461,NaN,200.0,8,1,0.418079,0.086378,-0.474785,...,0.109666,-0.219075,0.702251,0.223935,0.188982,0.795413,0.035039,-0.281826,0.724600,0.160558

In [23]:
footage_samples = df.groupby("filename").groups.keys()
print(footage_samples)

dict_keys(['a_andrade_188cm_454kg_rpe8.mp4', 'a_andrade_188cm_470kg_rpe9.mp4', 'a_andrade_400kg_188cm_rpe7.mp4', 'a_andrade_420kg_188cm_rpe7.mp4', 'a_bishop_191cm_454kg_rpe8.mp4', 'a_bishop_191cm_470kg_rpe9.mp4', 'a_bishop_400kg_191cm_rpe6.mp4', 'b_johnson_200cm_400kg_rpe7.mp4', 'b_johnson_200cm_420kg_rpe8.mp4', 'b_johnson_200cm_440kg_rpe8.mp4', 'ben_donin_350kg_rpe7.mp4', 'ben_donin_390kg_rpe10.mp4', 'deadlift_10_rpe10.mp4', 'deadlift_11_conventional_rpe5.mp4', 'deadlift_11_sumo_rpe5.mp4', 'deadlift_12_conventional_rpe5.mp4', 'deadlift_12_sumo_rpe5.mp4', 'deadlift_13_rpe5.mp4', 'deadlift_14_rpe5.mp4', 'deadlift_15_rpe5.mp4', 'deadlift_16_rpe5.mp4', 'deadlift_17_rpe5.mp4', 'deadlift_18_rpe5.mp4', 'deadlift_19_rpe5.mp4', 'deadlift_1_rpe5.mp4', 'deadlift_20_rpe5.mp4', 'deadlift_21_1rpe5.mp4', 'deadlift_21_2rpe5.mp4', 'deadlift_22_rpe5.mp4', 'deadlift_23_rpe5.mp4', 'deadlift_24_rpe5.mp4', 'deadlift_26_1rpe5.mp4', 'deadlift_26_2rpe5.mp4', 'deadlift_27_1rpe5.mp4', 'deadlift_27_2rpe5.mp4', 'deadlift_28_rpe8.mp4', 'deadlift_28_rpe9.mp4', 'deadlift_29_rpe5.mp4', 'deadlift_2_rpe5.mp4', 'deadlift_30_1rpe6.mp4', 'deadlift_30_2rpe6.mp4', 'deadlift_32_rpe10.mp4', 'deadlift_3_rpe5.mp4', 'deadlift_4_rpe5.mp4', 'deadlift_5_rpe5.mp4', 'deadlift_6_rpe5.mp4', 'deadlift_7_rpe5.mp4', 'deadlift_8_rpe5.mp4', 'deadlift_9_rpe6.mp4', 'eamonn_rpe8.mp4', 'eddie_williams_400kg_193cm_rpe8.mp4', 'eddie_williams_420kg_193cm_rpe8.mp4', 'elbel_370kg_rpe7.mp4', 'elbel_390kg_rpe8.mp4', 'g_bilton_400kg_200cm_rpe7.mp4', 'g_bilton_420kg_200cm_rpe8.mp4', 'g_bilton_440kg_200cm_rpe9.mp4', 'harford_350kg_rpe8.mp4', 'heinla_183cm_400kg_rpe7.mp4', 'heinla_183cm_420kg_rpe8.mp4', 'heinla_183cm_440kg_rpe8.mp4', 'heinla_183cm_460kg_rpe9.mp4', 'hilmar_360kg_rpe8.mp4', 'jiruze_180cm_400kg_rpe7.mp4', 'jiruze_180cm_421kg_rpe8.mp4', 'jiruze_180cm_430kg_rpe8.mp4', 'john_haack_175cm_365kg_rpe8.mp4', 'john_haack_175kg_400kg_rpe9.mp4', 'lacina_380kg_rpe7.mp4', 'lstoltman_400kg_191cm_rpe8.mp4', 'm_ragg_188cm_420kg_rpe8.mp4', 'm_ragg_188cm_454kg_rpe9.mp4', 'm_ragg_400kg_188cm_rpe7.mp4', 'makarov_182cm_410kg_rpe8.mp4', 'makarov_182cm_454kg_rpe9.mp4', 'misha_186cm_400kg_rpe10.mp4', 'paddyhaines_191cm_440kg_rpe9.mp4', 'paddyhaines_191cm_454kg_rpe10.mp4', 'paddyhaines_400kg_191cm_rpe7.mp4', 'paddyhaines_420kg_191cm_rpe7.mp4', 'random_405kg_rpe10.mp4', 'random_405kg_rpe7.mp4', 'raul_f_175cm_420kg_rpe8.mp4', 'raul_f_175cm_454kg_rpe8.mp4', 'shane_420kg_rpe7.mp4', 'shaw500training21_200cm_rpe8.mp4', 'shaw500training2_200cm_rpe8.mp4', 'shaw_2017_460kg_200cm_rpe10.mp4', 'shaw_414kg_200cm_rpe7.mp4', 'shaw_414kg_200cm_rpe8.mp4', 'shaw_480kg_200cm_rpe10.mp4', 'shaw_480kg_200cm_rpe8.mp4', 'shaw_arnold_1_200cm_rpe8.mp4', 'shaw_arnolds2013_1_200cm_rpe7.mp4', 'shaw_arnolds2013_2_200cm_rpe9.mp4', 'shaw_arnolds2013_3_200cm_rpe9.mp4', 'shaw_arnolds_2014_200cm_rpe9.mp4', 'shaw_arnolds_2016_200cm_rpe9.mp4', 'shaw_car10_200cm_rpe8.mp4', 'shaw_car1_200cm_rpe6.mp4', 'shaw_car2_200cm_rpe7.mp4', 'shaw_car3_1_200cm_rpe7.mp4', 'shaw_car3_200cm_rpe7.mp4', 'shaw_car3_2_200cm_rpe8.mp4', 'shaw_car3_3_200cm_rpe8.mp4', 'shaw_car3_4_200cm_rpe8.mp4', 'shaw_car3_5_200cm_rpe9.mp4', 'shaw_car4_1_200cm_rpe7.mp4', 'shaw_car4_200cm_rpe7.mp4', 'shaw_car4_2_200cm_rpe8.mp4', 'shaw_car4_4_200cm_rpe8.mp4', 'shaw_car4_5_200cm_rpe8.mp4', 'shaw_car4_7_200cm_rpe9.mp4', 'shaw_car5_200cm_rpe7.mp4', 'shaw_car6_200cm_rpe7.mp4', 'shaw_car7_200cm_rpe7.mp4', 'shaw_car8_200cm_rpe7.mp4', 'shaw_car9_200cm_rpe8.mp4', 'singleton_198cm_420kg_rpe7.mp4', 't_hoath_400kg_188cm_rpe8.mp4', 't_hoath_420kg_188cm_rpe9.mp4', 'thor-120kg_rpe5_204cm.mp4', 'thor-170kg_rpe5_204cm.mp4', 'thor-220kg_rpe5_204cm.mp4', 'thor-325kg_rpe5_204cm.mp4', 'thor-375kg_rpe6_204cm.mp4', 'thor-420kg_rpe7_204cm.mp4', 'thor-465kg_rpe8_204cm.mp4', 'thor-501kg_rpe9_204cm.mp4', 'thor-70kg_rpe5_204cm.mp4', 'thor_2019_470kg_204cm_rpe9.mp4', 'thor_2025_200cm_420kg_rpe6.mp4', 'thor_2025_204cm_470kg_rpe7.mp4', 'thor_2025_204cm_510kg_rpe8.mp4', 'thor_2025_435kg_204cm_rpe7.mp4', 'thor_2025_470kg_rpe8.mp4', 'thor_204cm_505kg_rpe9.mp4', 'thor_454kg_204cm_rpe9.mp4', 'thor_455kg_200cm_rpe10.mp4', 'thor_470kg_204cm_rpe8.mp4', 'vladimir_370kg_rpe8.mp4', 'vladmir_360kg_rpe8.mp4'])

In [46]:
from types import SimpleNamespace as NS
import numpy as np

N_LANDMARKS = 33
fake_frame = np.zeros((720, 1280, 3), dtype=np.uint8)

def row_to_estimation(r):
    if not r["detected"]:
        return NS(pose_landmarks=[], pose_world_landmarks=[])
    img = [NS(x=r[f"img{i}_x"], y=r[f"img{i}_y"], z=r[f"img{i}_z"],
              visibility=1.0, presence=1.0) for i in range(N_LANDMARKS)]
    world = [NS(x=r[f"world{i}_x"], y=r[f"world{i}_y"], z=r[f"world{i}_z"],
                visibility=1.0, presence=1.0) for i in range(N_LANDMARKS)]
    return NS(pose_landmarks=[img], pose_world_landmarks=[world])

In [71]:
metrics_by_footage = {}

for footage_sample in footage_samples:
    try:
        footage_df = df[df.filename == footage_sample].sort_values("frame")
        height = footage_df.height.iloc[0] or 0.0
        rpe = footage_df.rpe.iloc[0]
        print(f"Estimating metrics for {footage_sample} [ height: {height}, rpe: {rpe}")

        metrics = liftanalyzer.metrics.mediapipe_metrics.MediapipeMetrics()
        if pd.notna(height) and height > 0:
            estimated_frames = [(fake_frame, row_to_estimation(r)) for _, r in footage_df.iterrows()]
            metrics.calibrate_scale(height / 100.0, estimated_frames)
        history = None

        for _, r in footage_df.iterrows():
            estimation = row_to_estimation(r)
            timestamp = int(r["time_s"] * 1e9) 
            history = metrics.get_metrics(fake_frame, estimation, timestamp)
        rep_ranges = liftanalyzer.utils.biomechanics.get_rep_ranges(EXERCISE, history)
        average_velocity = metrics.get_average_velocity(history, rep_ranges)
        peak_velocity = metrics.get_peak_velocity(history, rep_ranges)
        metrics_by_footage[footage_sample] = { "rpe": rpe, "average_velocity": average_velocity, "peak_velocity": peak_velocity }
    except Exception as e:
        print(e)

Estimating metrics for a_andrade_188cm_454kg_rpe8.mp4 [ height: 188.0, rpe: 8
calibrated: 200.6 px/m (H=1.88 m, n=2 segments)
Estimating metrics for a_andrade_188cm_470kg_rpe9.mp4 [ height: 188.0, rpe: 9
calibrated: 211.9 px/m (H=1.88 m, n=2 segments)
Estimating metrics for a_andrade_400kg_188cm_rpe7.mp4 [ height: 188.0, rpe: 7
calibrated: 203.2 px/m (H=1.88 m, n=2 segments)
Estimating metrics for a_andrade_420kg_188cm_rpe7.mp4 [ height: 188.0, rpe: 7
calibrated: 205.9 px/m (H=1.88 m, n=2 segments)
Estimating metrics for a_bishop_191cm_454kg_rpe8.mp4 [ height: 191.0, rpe: 8
calibrated: 207.2 px/m (H=1.91 m, n=2 segments)
Estimating metrics for a_bishop_191cm_470kg_rpe9.mp4 [ height: 191.0, rpe: 9
calibrated: 221.2 px/m (H=1.91 m, n=2 segments)
Estimating metrics for a_bishop_400kg_191cm_rpe6.mp4 [ height: 191.0, rpe: 6
calibrated: 210.1 px/m (H=1.91 m, n=2 segments)
Estimating metrics for b_johnson_200cm_400kg_rpe7.mp4 [ height: 200.0, rpe: 7
calibrated: 212.1 px/m (H=2.00 m, n=2 segments)
Estimating metrics for b_johnson_200cm_420kg_rpe8.mp4 [ height: 200.0, rpe: 8
calibrated: 205.0 px/m (H=2.00 m, n=2 segments)
Estimating metrics for b_johnson_200cm_440kg_rpe8.mp4 [ height: 200.0, rpe: 8
calibrated: 205.6 px/m (H=2.00 m, n=2 segments)
Estimating metrics for ben_donin_350kg_rpe7.mp4 [ height: nan, rpe: 7
Estimating metrics for ben_donin_390kg_rpe10.mp4 [ height: nan, rpe: 10
Estimating metrics for deadlift_10_rpe10.mp4 [ height: nan, rpe: 10
Estimating metrics for deadlift_11_conventional_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_11_sumo_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_12_conventional_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_12_sumo_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_13_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_14_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_15_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_16_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_17_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_18_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_19_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_1_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_20_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_21_1rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_21_2rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_22_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_23_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_24_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_26_1rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_26_2rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_27_1rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_27_2rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_28_rpe8.mp4 [ height: nan, rpe: 8
Estimating metrics for deadlift_28_rpe9.mp4 [ height: nan, rpe: 9
Estimating metrics for deadlift_29_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_2_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_30_1rpe6.mp4 [ height: nan, rpe: 6
Estimating metrics for deadlift_30_2rpe6.mp4 [ height: nan, rpe: 6
Estimating metrics for deadlift_32_rpe10.mp4 [ height: nan, rpe: 10
Estimating metrics for deadlift_3_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_4_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_5_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_6_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_7_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_8_rpe5.mp4 [ height: nan, rpe: 5
Estimating metrics for deadlift_9_rpe6.mp4 [ height: nan, rpe: 6
Estimating metrics for eamonn_rpe8.mp4 [ height: nan, rpe: 8
Estimating metrics for eddie_williams_400kg_193cm_rpe8.mp4 [ height: 193.0, rpe: 8
calibrated: 212.7 px/m (H=1.93 m, n=2 segments)
Estimating metrics for eddie_williams_420kg_193cm_rpe8.mp4 [ height: 193.0, rpe: 8
calibrated: 212.0 px/m (H=1.93 m, n=2 segments)
Estimating metrics for elbel_370kg_rpe7.mp4 [ height: nan, rpe: 7
Estimating metrics for elbel_390kg_rpe8.mp4 [ height: nan, rpe: 8
Estimating metrics for g_bilton_400kg_200cm_rpe7.mp4 [ height: 200.0, rpe: 7
calibrated: 212.9 px/m (H=2.00 m, n=2 segments)
Estimating metrics for g_bilton_420kg_200cm_rpe8.mp4 [ height: 200.0, rpe: 8
calibrated: 214.9 px/m (H=2.00 m, n=2 segments)
Estimating metrics for g_bilton_440kg_200cm_rpe9.mp4 [ height: 200.0, rpe: 9
calibrated: 216.2 px/m (H=2.00 m, n=2 segments)
Estimating metrics for harford_350kg_rpe8.mp4 [ height: nan, rpe: 8
Estimating metrics for heinla_183cm_400kg_rpe7.mp4 [ height: 183.0, rpe: 7
calibrated: 231.0 px/m (H=1.83 m, n=2 segments)
Estimating metrics for heinla_183cm_420kg_rpe8.mp4 [ height: 183.0, rpe: 8
calibrated: 323.5 px/m (H=1.83 m, n=2 segments)
Estimating metrics for heinla_183cm_440kg_rpe8.mp4 [ height: 183.0, rpe: 8
calibrated: 211.9 px/m (H=1.83 m, n=2 segments)
Estimating metrics for heinla_183cm_460kg_rpe9.mp4 [ height: 183.0, rpe: 9
calibrated: 280.9 px/m (H=1.83 m, n=2 segments)
Estimating metrics for hilmar_360kg_rpe8.mp4 [ height: nan, rpe: 8
Estimating metrics for jiruze_180cm_400kg_rpe7.mp4 [ height: 180.0, rpe: 7
calibrated: 336.3 px/m (H=1.80 m, n=2 segments)
Estimating metrics for jiruze_180cm_421kg_rpe8.mp4 [ height: 180.0, rpe: 8
calibrated: 284.6 px/m (H=1.80 m, n=2 segments)
Estimating metrics for jiruze_180cm_430kg_rpe8.mp4 [ height: 180.0, rpe: 8
calibrated: 330.5 px/m (H=1.80 m, n=2 segments)
Estimating metrics for john_haack_175cm_365kg_rpe8.mp4 [ height: 175.0, rpe: 8
calibrated: 336.3 px/m (H=1.75 m, n=2 segments)
Estimating metrics for john_haack_175kg_400kg_rpe9.mp4 [ height: nan, rpe: 9
Estimating metrics for lacina_380kg_rpe7.mp4 [ height: nan, rpe: 7
Estimating metrics for lstoltman_400kg_191cm_rpe8.mp4 [ height: 191.0, rpe: 8
calibrated: 215.3 px/m (H=1.91 m, n=2 segments)
Estimating metrics for m_ragg_188cm_420kg_rpe8.mp4 [ height: 188.0, rpe: 8
calibrated: 213.5 px/m (H=1.88 m, n=2 segments)
Estimating metrics for m_ragg_188cm_454kg_rpe9.mp4 [ height: 188.0, rpe: 9
calibrated: 217.9 px/m (H=1.88 m, n=2 segments)
Estimating metrics for m_ragg_400kg_188cm_rpe7.mp4 [ height: 188.0, rpe: 7
calibrated: 219.3 px/m (H=1.88 m, n=2 segments)
Estimating metrics for makarov_182cm_410kg_rpe8.mp4 [ height: 182.0, rpe: 8
calibrated: 277.9 px/m (H=1.82 m, n=2 segments)
Estimating metrics for makarov_182cm_454kg_rpe9.mp4 [ height: 182.0, rpe: 9
calibrated: 288.6 px/m (H=1.82 m, n=2 segments)
Estimating metrics for misha_186cm_400kg_rpe10.mp4 [ height: 186.0, rpe: 10
calibrated: 321.3 px/m (H=1.86 m, n=2 segments)
Estimating metrics for paddyhaines_191cm_440kg_rpe9.mp4 [ height: 191.0, rpe: 9
calibrated: 206.9 px/m (H=1.91 m, n=2 segments)
Estimating metrics for paddyhaines_191cm_454kg_rpe10.mp4 [ height: 191.0, rpe: 10
calibrated: 203.1 px/m (H=1.91 m, n=2 segments)
Estimating metrics for paddyhaines_400kg_191cm_rpe7.mp4 [ height: 191.0, rpe: 7
calibrated: 209.3 px/m (H=1.91 m, n=2 segments)
Estimating metrics for paddyhaines_420kg_191cm_rpe7.mp4 [ height: 191.0, rpe: 7
calibrated: 215.4 px/m (H=1.91 m, n=2 segments)
Estimating metrics for random_405kg_rpe10.mp4 [ height: nan, rpe: 10
Estimating metrics for random_405kg_rpe7.mp4 [ height: nan, rpe: 7
Estimating metrics for raul_f_175cm_420kg_rpe8.mp4 [ height: 175.0, rpe: 8
calibrated: 210.6 px/m (H=1.75 m, n=2 segments)
Estimating metrics for raul_f_175cm_454kg_rpe8.mp4 [ height: 175.0, rpe: 8
calibrated: 211.9 px/m (H=1.75 m, n=2 segments)
Estimating metrics for shane_420kg_rpe7.mp4 [ height: nan, rpe: 7
Estimating metrics for shaw500training21_200cm_rpe8.mp4 [ height: 200.0, rpe: 8
calibrated: 289.4 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw500training2_200cm_rpe8.mp4 [ height: 200.0, rpe: 8
calibrated: 288.6 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_2017_460kg_200cm_rpe10.mp4 [ height: 200.0, rpe: 10
calibrated: 264.5 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_414kg_200cm_rpe7.mp4 [ height: 200.0, rpe: 7
calibrated: 280.0 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_414kg_200cm_rpe8.mp4 [ height: 200.0, rpe: 8
calibrated: 280.7 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_480kg_200cm_rpe10.mp4 [ height: 200.0, rpe: 10
calibrated: 285.4 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_480kg_200cm_rpe8.mp4 [ height: 200.0, rpe: 8
calibrated: 291.8 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_arnold_1_200cm_rpe8.mp4 [ height: 200.0, rpe: 8
calibrated: 278.1 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_arnolds2013_1_200cm_rpe7.mp4 [ height: 200.0, rpe: 7
calibrated: 258.9 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_arnolds2013_2_200cm_rpe9.mp4 [ height: 200.0, rpe: 9
calibrated: 246.9 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_arnolds2013_3_200cm_rpe9.mp4 [ height: 200.0, rpe: 9
calibrated: 261.3 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_arnolds_2014_200cm_rpe9.mp4 [ height: 200.0, rpe: 9
calibrated: 291.0 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_arnolds_2016_200cm_rpe9.mp4 [ height: 200.0, rpe: 9
calibrated: 432.8 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car10_200cm_rpe8.mp4 [ height: 200.0, rpe: 8
calibrated: 342.4 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car1_200cm_rpe6.mp4 [ height: 200.0, rpe: 6
calibrated: 377.2 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car2_200cm_rpe7.mp4 [ height: 200.0, rpe: 7
calibrated: 379.2 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car3_1_200cm_rpe7.mp4 [ height: 200.0, rpe: 7
calibrated: 341.0 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car3_200cm_rpe7.mp4 [ height: 200.0, rpe: 7
calibrated: 378.7 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car3_2_200cm_rpe8.mp4 [ height: 200.0, rpe: 8
calibrated: 339.9 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car3_3_200cm_rpe8.mp4 [ height: 200.0, rpe: 8
calibrated: 339.2 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car3_4_200cm_rpe8.mp4 [ height: 200.0, rpe: 8
calibrated: 338.3 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car3_5_200cm_rpe9.mp4 [ height: 200.0, rpe: 9
calibrated: 336.9 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car4_1_200cm_rpe7.mp4 [ height: 200.0, rpe: 7
calibrated: 316.0 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car4_200cm_rpe7.mp4 [ height: 200.0, rpe: 7
calibrated: 377.0 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car4_2_200cm_rpe8.mp4 [ height: 200.0, rpe: 8
calibrated: 322.4 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car4_4_200cm_rpe8.mp4 [ height: 200.0, rpe: 8
calibrated: 321.0 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car4_5_200cm_rpe8.mp4 [ height: 200.0, rpe: 8
calibrated: 319.6 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car4_7_200cm_rpe9.mp4 [ height: 200.0, rpe: 9
calibrated: 327.5 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car5_200cm_rpe7.mp4 [ height: 200.0, rpe: 7
calibrated: 378.7 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car6_200cm_rpe7.mp4 [ height: 200.0, rpe: 7
calibrated: 346.6 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car7_200cm_rpe7.mp4 [ height: 200.0, rpe: 7
calibrated: 345.8 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car8_200cm_rpe7.mp4 [ height: 200.0, rpe: 7
calibrated: 344.7 px/m (H=2.00 m, n=2 segments)
Estimating metrics for shaw_car9_200cm_rpe8.mp4 [ height: 200.0, rpe: 8
calibrated: 344.5 px/m (H=2.00 m, n=2 segments)
Estimating metrics for singleton_198cm_420kg_rpe7.mp4 [ height: 198.0, rpe: 7
calibrated: 199.2 px/m (H=1.98 m, n=2 segments)
Estimating metrics for t_hoath_400kg_188cm_rpe8.mp4 [ height: 188.0, rpe: 8
calibrated: 212.6 px/m (H=1.88 m, n=2 segments)
Estimating metrics for t_hoath_420kg_188cm_rpe9.mp4 [ height: 188.0, rpe: 9
calibrated: 202.5 px/m (H=1.88 m, n=2 segments)
Estimating metrics for thor-120kg_rpe5_204cm.mp4 [ height: 204.0, rpe: 5
calibrated: 417.9 px/m (H=2.04 m, n=2 segments)
Estimating metrics for thor-170kg_rpe5_204cm.mp4 [ height: 204.0, rpe: 5
calibrated: 419.6 px/m (H=2.04 m, n=2 segments)
Estimating metrics for thor-220kg_rpe5_204cm.mp4 [ height: 204.0, rpe: 5
calibrated: 402.8 px/m (H=2.04 m, n=2 segments)
Estimating metrics for thor-325kg_rpe5_204cm.mp4 [ height: 204.0, rpe: 5
calibrated: 337.2 px/m (H=2.04 m, n=2 segments)
Estimating metrics for thor-375kg_rpe6_204cm.mp4 [ height: 204.0, rpe: 6
calibrated: 311.5 px/m (H=2.04 m, n=2 segments)
Estimating metrics for thor-420kg_rpe7_204cm.mp4 [ height: 204.0, rpe: 7
calibrated: 235.7 px/m (H=2.04 m, n=2 segments)
Estimating metrics for thor-465kg_rpe8_204cm.mp4 [ height: 204.0, rpe: 8
calibrated: 258.5 px/m (H=2.04 m, n=2 segments)
Estimating metrics for thor-501kg_rpe9_204cm.mp4 [ height: 204.0, rpe: 9
calibrated: 242.2 px/m (H=2.04 m, n=2 segments)
Estimating metrics for thor-70kg_rpe5_204cm.mp4 [ height: 204.0, rpe: 5
calibrated: 387.5 px/m (H=2.04 m, n=2 segments)
Estimating metrics for thor_2019_470kg_204cm_rpe9.mp4 [ height: 204.0, rpe: 9
calibrated: 314.1 px/m (H=2.04 m, n=2 segments)
Estimating metrics for thor_2025_200cm_420kg_rpe6.mp4 [ height: 200.0, rpe: 6
calibrated: 220.9 px/m (H=2.00 m, n=2 segments)
Estimating metrics for thor_2025_204cm_470kg_rpe7.mp4 [ height: 204.0, rpe: 7
calibrated: 207.8 px/m (H=2.04 m, n=2 segments)
Estimating metrics for thor_2025_204cm_510kg_rpe8.mp4 [ height: 204.0, rpe: 8
calibrated: 220.7 px/m (H=2.04 m, n=2 segments)
Estimating metrics for thor_2025_435kg_204cm_rpe7.mp4 [ height: 204.0, rpe: 7
calibrated: 349.5 px/m (H=2.04 m, n=2 segments)
Estimating metrics for thor_2025_470kg_rpe8.mp4 [ height: nan, rpe: 8
Estimating metrics for thor_204cm_505kg_rpe9.mp4 [ height: 204.0, rpe: 9
calibrated: 312.2 px/m (H=2.04 m, n=2 segments)
Estimating metrics for thor_454kg_204cm_rpe9.mp4 [ height: 204.0, rpe: 9
calibrated: 336.3 px/m (H=2.04 m, n=2 segments)
Estimating metrics for thor_455kg_200cm_rpe10.mp4 [ height: 200.0, rpe: 10
calibrated: 309.4 px/m (H=2.00 m, n=2 segments)
Estimating metrics for thor_470kg_204cm_rpe8.mp4 [ height: 204.0, rpe: 8
calibrated: 313.1 px/m (H=2.04 m, n=2 segments)
Estimating metrics for vladimir_370kg_rpe8.mp4 [ height: nan, rpe: 8
Estimating metrics for vladmir_360kg_rpe8.mp4 [ height: nan, rpe: 8

In [79]:
velocity_rpe_df = pd.DataFrame(metrics_by_footage).T

In [93]:
out = velocity_rpe_df[["average_velocity", "peak_velocity", "rpe"]].copy()
out["rpe"] = out["rpe"].astype(int).astype(str).replace({"5": "<5"})
out

                                average_velocity  peak_velocity rpe
a_andrade_188cm_454kg_rpe8.mp4          0.229337       0.331736   8
a_andrade_188cm_470kg_rpe9.mp4          0.159738       0.308038   9
a_andrade_400kg_188cm_rpe7.mp4          0.346808       0.521046   7
a_andrade_420kg_188cm_rpe7.mp4          0.310702       0.464875   7
a_bishop_191cm_454kg_rpe8.mp4           0.219868       0.411419   8
...                                          ...            ...  ..
thor_454kg_204cm_rpe9.mp4               0.130034       0.333431   9
thor_455kg_200cm_rpe10.mp4              0.123358       0.182729  10
thor_470kg_204cm_rpe8.mp4               0.285099       0.407794   8
vladimir_370kg_rpe8.mp4                 0.051486       0.191305   8
vladmir_360kg_rpe8.mp4                  0.112638       0.272592   8

[142 rows x 3 columns]

In [92]:
out.to_csv("./data"index=False, header=False)

'0.22933693905128455,0.33173617094689617,8\n0.1597383208445731,0.3080382823389719,9\n0.3468075844748047,0.521045588161066,7\n0.3107023783835206,0.4648746695653772,7\n0.2198681825598272,0.41141891671373004,8\n0.2213100219921527,0.32040862233444806,9\n0.3767987233249024,0.5990793472812492,6\n0.3852710510101735,0.5661089451040257,7\n0.3206830362733487,0.45997706723092047,8\n0.203653436603936,0.35935308664823423,8\n0.11841565129565713,0.2975491118921823,7\n0.09101468596803629,0.21673933495283623,10\n0.2449062310267411,0.34238327557891374,10\n0.22358533524180327,0.3531642168644483,<5\n0.14174706849487645,0.20009178674411826,<5\n0.2798258016457283,0.37743345616375273,<5\n0.1746242609694457,0.2905446682109079,<5\n0.17527688155685775,0.30339157223392976,<5\n0.17321016452271484,0.328990227898475,<5\n0.5433721929091251,0.9798455554681866,<5\n0.15615379411856414,0.2023652420947852,<5\n0.2770320572861354,0.3828420396913101,<5\n0.1310359938627007,0.3180580241277655,<5\n0.16489489387237372,0.41293888997083394,<5\n0.22699436974323184,0.3483797289724899,<5\n0.30314988039702767,0.35048270710824664,<5\n0.246582100539686,0.34744829881384726,<5\n0.15205508617766286,0.22356105367566761,<5\n0.15805513121102016,0.2770584992587968,<5\n0.5710115881999417,0.714517046366362,<5\n0.5314030463252648,0.8943839378951791,<5\n0.30666359697081785,0.40507854472784693,<5\n0.25721621021966967,0.3154095552885928,<5\n0.2939952802609409,0.46417863962963246,<5\n0.3081170468043323,0.4663751694405441,<5\n0.10582294515770695,0.24441195608837557,8\n0.07976525497173993,0.17408020290771625,9\n0.3939604215798075,0.5539949597910484,<5\n0.2515524091471029,0.38472500518418934,<5\n0.20605336964721133,0.2867777597655081,6\n0.27630942803255215,0.32776323361057924,6\n0.0752651539645839,0.13181687978572043,10\n0.2159097321181122,0.31407053380371885,<5\n0.20176897405009533,0.25614063772268636,<5\n0.20037238582661676,0.2467208993185939,<5\n0.10710696707191751,0.2979861732250022,<5\n0.15467912647664395,0.39141264208187115,<5\n0.3763324287493041,0.7121307701593254,<5\n0.15969632649299165,0.3725320825961743,6\n0.0699230928015654,0.14836159998683215,8\n0.16789599171784397,0.29170764408549904,8\n0.19041449609344968,0.32969184383133676,8\n0.1260330412465976,0.26267735028609107,7\n0.12726646711038406,0.28032488416698137,8\n0.3337026357979748,0.5034193962833076,7\n0.2582563302404232,0.37588829389160405,8\n0.12411962029681599,0.27000154591480924,9\n0.09195541187989725,0.24873196026486652,8\n0.3276510059655224,0.47314261579338157,7\n0.29829775247075263,0.38651439819957445,8\n0.2609993284533825,0.33217290363461793,8\n0.16633088573455843,0.24993455507440757,9\n0.1623131567935846,0.239396696608301,8\n0.38936345405052575,0.5199552123177569,7\n0.21639846975209248,0.31505266235687923,8\n0.16813975606881224,0.30858274051888546,8\n0.2246552915830786,0.325341862264787,8\n0.07279888251248719,0.22022586062555025,9\n0.10525820555264885,0.2436862048523358,7\n0.2088289900559987,0.35995698611617694,8\n0.24244623946351518,0.35303152169973906,8\n0.1333930139792956,0.2638837960286189,9\n0.3202331070667083,0.4211731280281654,7\n0.39261629597628217,0.5067256492931803,8\n0.13229757227764866,0.21430653212743794,9\n0.12845656240784462,0.19218103957980448,10\n0.15920725351720028,0.29530291769123607,9\n0.12268370916401367,0.28364265581552384,10\n0.3236498594213958,0.46987737832030047,7\n0.37102038678531446,0.4381551103318191,7\n0.06256968030739982,0.15080256211545423,10\n0.14946577646739728,0.23008217214233972,7\n0.23581148410468272,0.33111646130693806,8\n0.16292899961827045,0.25522434666565386,8\n0.0947929602562275,0.14009198003349269,7\n0.26746024558654113,0.4020122877639584,8\n0.25394020714139837,0.42649816643743305,8\n0.14655496772428772,0.16709071412276458,10\n0.3187169821088053,0.5352708644510041,7\n0.3612986888974152,0.527352575994332,8\n0.14648265529414356,0.18577007629557923,10\n0.20802044896447985,0.3173953126474682,8\n0.30954962368167693,0.449337531810591,8\n0.20346230234241341,0.34283669548478213,7\n0.15329578134126773,0.23042046690774567,9\n0.1299998079000126,0.21116186493636754,9\n0.1424774557811055,0.26951911503887693,9\n-0.031990396075675234,0.0676373825515007,9\n0.3762702206165724,0.5557228179241791,8\n0.4525258202144386,0.6467546845425985,6\n0.4578956137784587,0.6594246147693583,7\n0.32468341128780526,0.5256248842011323,7\n0.4795828381793661,0.65536989488511,7\n0.21848884528457954,0.5238695251414708,8\n0.27239880648634573,0.4982273729918696,8\n0.2672833644819138,0.5106136319881999,8\n0.2647773830817048,0.46746482481282875,9\n0.3647440233612866,0.42256700447192125,7\n0.43264175026221,0.6385444825478062,7\n0.32407785511955456,0.4787676843439956,8\n0.2552855232815237,0.44414002482599574,8\n0.18653779059337727,0.42216743111354726,8\n0.19740994623241098,0.37441827779076986,9\n0.4691342120591236,0.6528444334901364,7\n0.37326279949358865,0.6055440835235456,7\n0.4130270309452254,0.6059383641681199,7\n0.36177791961470335,0.6286241151757728,7\n0.41414859311708013,0.5714326404443681,8\n0.40146168550542377,0.5626203591420076,7\n0.2451719241969721,0.27651126151345556,8\n0.1385975999367857,0.22006606571738316,9\n0.4495049975489505,0.7540701533012798,<5\n0.520000660307462,0.5965297270720653,<5\n0.532842623327536,0.6252013063221582,<5\n0.5097110543516465,0.6653128201264905,<5\n0.3967154130343934,0.655566113623097,6\n0.4465623413575718,0.614145777465664,7\n0.3751012787201764,0.47083392623673165,8\n0.18407520747404427,0.29175221104389376,9\n0.6035925262413481,0.6408004633117191,<5\n0.08087212440989681,0.2444370158423966,9\n0.407370575387061,0.6164577190070969,6\n0.3328676740976678,0.503714661090525,7\n0.24222844342702282,0.3259560373424691,8\n0.36068057885052623,0.615932072023303,7\n0.06924195468294443,0.1806788562591946,8\n0.1815031746218513,0.27262221072484116,9\n0.1300339536264048,0.3334306857685548,9\n0.12335813988370317,0.1827291675840289,10\n0.285099325526604,0.4077935594899173,8\n0.051485688148931445,0.1913054693122047,8\n0.11263775256903438,0.27259243011150697,8\n'